version: "3.8"
services:
  server:
    build:
      context: ./dir
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    links:
      - mongo
    environment:
      - PORT: 3030
      - MONGO_URL: mongodb://mongo/todo
  mongo:
    image: mongo
    ports:
      - "27017:27017"